# Generated by Django 4.2 on 2023-04-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="first_cup",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="titles",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
